In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8324, 9811, 8181, 349],
 [8324, 9811, 8181, 1220],
 [8324, 167, 8181, 3313],
 [8794, 2553, 7710, 2084, 252],
 [8794, 2553, 7710, 2084, 8008],
 [560, 8324, 8298, 8181, 9261],
 [4740, 2438, 3714, 2084]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8324 9811 8181  349]
 [   0    0    0    0 8324 9811 8181 1220]
 [   0    0    0    0 8324  167 8181 3313]
 [   0    0    0 8794 2553 7710 2084  252]
 [   0    0    0 8794 2553 7710 2084 8008]
 [   0    0    0  560 8324 8298 8181 9261]
 [   0    0    0    0 4740 2438 3714 2084]]


In [11]:
## Feature representation
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step


array([[[-0.02317095,  0.0325149 , -0.00248273,  0.03268984,
          0.03623346, -0.03551739, -0.00943445, -0.03459239,
          0.01734115,  0.00858932],
        [-0.02317095,  0.0325149 , -0.00248273,  0.03268984,
          0.03623346, -0.03551739, -0.00943445, -0.03459239,
          0.01734115,  0.00858932],
        [-0.02317095,  0.0325149 , -0.00248273,  0.03268984,
          0.03623346, -0.03551739, -0.00943445, -0.03459239,
          0.01734115,  0.00858932],
        [-0.02317095,  0.0325149 , -0.00248273,  0.03268984,
          0.03623346, -0.03551739, -0.00943445, -0.03459239,
          0.01734115,  0.00858932],
        [-0.00169202, -0.03291349,  0.04793528, -0.02546779,
          0.04314593, -0.04964193,  0.03020277, -0.0428227 ,
         -0.03125498, -0.021047  ],
        [-0.02646207,  0.00826482,  0.0477507 ,  0.01977618,
          0.01573333,  0.03519725,  0.02765465, -0.03684112,
          0.03688916,  0.03363185],
        [ 0.01154107,  0.03611265, -0.03725427,  0.0

In [36]:
output = model.predict(embedded_docs)
print(output.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
(7, 8, 10)
